---
- hosts: winservers 
  tasks:
    # Install/uninstall with chocolatey
    - name: Ensure 7-Zip is installed via Chocolatey
      win_chocolatey:
        name: 7zip
        state: present
    # Copy folder contents recursively
    - name: Copy Artifact Folder
      ansible.windows.win_copy:
        src: bin/Debug/net6.0/publish/
        dest: C:\inetpub\wwwroot\
    # # Start a website
    # - name: newMVC IIS site
    #   win_iis_website:
    #     name: newMVC
    #     state: started
    #     port: 80
    #     ip: 127.0.0.1
    #     hostname: newmvc.local
    #     application_pool: newMVC
    #     physical_path: C:\sites\newMVC
    #     parameters: logfile.directory:C:\sites\logs
    #   register: website

...
