---
- hosts: winservers 
  tasks:
    # Install/uninstall with chocolatey
    - name: Ensure 7-Zip is installed via Chocolatey
      win_chocolatey:
        name: 7zip
        state: present
    # Copy folder contents recursively
    - name: Copy Artifacts
      win_copy:
        src:  bin/Debug/net6.0/publish/
        dest: C:\inetpub\wwwroot\newMVC
    # # Remove Default Web Site and the standard port 80 binding
    # - name: Remove Default Web Site
    #   win_iis_website:
    #     name: "Default Web Site"
    #     state: absent
    # Start a website
    - name: newMVC IIS site
      win_iis_website:
        name: newMVC
        state: started
        port: 80
        ip: All Unassigned
        application_pool: newMVC
        physical_path: C:\inetpub\wwwroot\newMVC
      register: website

...
